### ISSUE TITLE
Swipe up to close

### ISSUE THREAD

**Issue by pavelnaumov** [terrysahaidak/react-native-gallery-toolkit#23]
Hi @terrysahaidak ! Amazing library, really smooth-working!
I have a little question: do you think it would be possible to implement a feature like swiping up to close the gallery? Kind of like what you already have with the swipe down gesture. Or perhaps give me a few tips on how I can do it myself.
Thanks a lot in advance!
And thanks again for your great work 👍

**Comment by terrysahaidak** [comment]
Hi! Thank you. 

I already have something similar working. Check out `tr-lightbox` branch.

But you can also implement something on your own as well while this in development. The whole reason behind this project is to give some building blocks for everything you need and be as compostable as possible.

**Comment by pavelnaumov** [comment]
@terrysahaidak , thanks for your quick reply! I checked the `tr-lightbox` branch, exactly what I needed. Thanks a million man, really appreciate your help

**Comment by pavelnaumov** [comment]
For people that might be searching for something similar when creating/implementing a custom media viewer: check the example files of the `tr-lightbox` branch. The demo really shows the work: the lightbox is able to swipe in all direction, rendering a header (a footer would be possible too, I assume). It also uses the `react-native-fast-image` library out of the box which is great, too.
Honestly, @terrysahaidak, this is perhaps the greatest react-native gallery toolkit I have seen 👏🏻.

**Comment by terrysahaidak** [comment]
Thanks for the good words, I appreciate it.

Regarding fast-image, each component that renders some image has a `renderImage` callback in order to render any custom image you want.
While fast-image is quite popular, there are people I know who use their own custom modules for image rendering as well as some people who had problems with fast-image. Because of that, I don't want the library to depend on it and make sure you can always use whatever you want :)

**Comment by pavelnaumov** [comment]
That's super, thanks a lot! 🙏🏻
